spring.profiles.active: local

version: 0.4.2

spring:
  config:
    import:
      - mysql.yml
      - swagger.yml
      - crypto.yml
#      - liquibase.yml
      - mail.yml
      - redis.yml
      - jwt.yml
      - s3.yml
      - kakaowork.yml
      - thread.yml
      - monitoring.yml
  data:
    web:
      pageable:
        one-indexed-parameters: true

server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 10000
    threads:
      max: 200
      min-spare: 20
  error:
    include-stacktrace: on_param
    include-message: always
    path: /error

---
spring.config.activate.on-profile: local

spring:
  config:
    import:
      - optional:classpath:env.properties

logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: dev

logging:
  level:
    root: INFO
  structured:
    format:
      console: ecs
      file: ecs
  file:
    path: ${LOG_FILE_PATH:./logs}

---
spring.config.activate.on-profile: prod
